name: "Set Issue Label"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       - uses: Naturalclar/issue-action@v2.0.2
         with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["Requesting access to", "error" , "error"], "labels": ["Repository Access"], "assignees": ["username"]}, {"keywords": ["help", "limited"], "labels": ["help-wanted"], "assignees": ["username"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Job2: 
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "hello how are you!!!"
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            👋 @{{ author }}
            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpened: >
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible
        
        
          

                   
        
     
   
   
   
   #env:
       # MY_VAR: Hi there! My name is
        #FIRST_NAME: Mona
        #MIDDLE_NAME: The
        #LAST_NAME: Octocat
        #run: |
        # echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    
