name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: Naturalclar/issue-action@v2.0.2
         with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["Requesting access to", "error"], "labels": ["Repository Access"], "assignees": ["username"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted from mahbub"], "assignees": ["username"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          issue-message: 'you seem to request access to a certain repository but the issue lacks information'
